# Generated by Django 3.0.7 on 2021-03-15 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='title',
            new_name='name',
        ),
    ]
