# Generated by Django 3.0.7 on 2021-02-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_auto_20210216_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unfinished', 'Необработанный'), ('finished', 'Обработанный')], default='unfinished', max_length=10),
        ),
    ]
