# Generated by Django 3.0.7 on 2021-02-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Необработанный', 'Необработанный'), ('Обработанный', 'Обработанный')], default='Необработанный', max_length=14),
        ),
    ]
