# Generated by Django 3.0.7 on 2021-02-17 12:37

from django.db import migrations


class Migration(migrations.Migration):

    def rename_order_status(apps, schema_editor):
        Order = apps.get_model('foodcartapp', 'Order')
        Order.objects.update(status='Необработанный')

    dependencies = [
        ('foodcartapp', '0043_auto_20210217_1536'),
    ]

    operations = [
        migrations.RunPython(rename_order_status),
    ]
