# Generated by Django 3.0.7 on 2021-02-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20210217_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Коментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Необработанный', 'Необработанный'), ('Обработанный', 'Обработанный')], default='Необработанный', max_length=14, verbose_name='Статус'),
        ),
    ]
