# Generated by Django 3.0.7 on 2021-02-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20210217_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('Электронно', 'Электронно'), ('Наличностью', 'Наличностью')], default='Наличностью', max_length=11, verbose_name='Способ оплаты'),
            preserve_default=False,
        ),
    ]
