# Generated by Django 3.0.7 on 2021-04-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_auto_20210407_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Необработанный', 'Необработанный'), ('Обработанный', 'Обработанный')], default='Необработанный', max_length=14, verbose_name='Статус'),
        ),
    ]
