# Generated by Django 3.0.7 on 2021-04-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_auto_20210407_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('Наличностью', 'Наличностью'), ('Электронно', 'Электронно')], max_length=11, verbose_name='Способ оплаты'),
        ),
    ]
